version: '3'

services:
  db:
    image: postgres
    container_name: postgres
    ports: 
      - 5432:5432
    restart: always
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fale_mais
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 10
    networks: 
      - fale_mais_api

  api: 
    build: ./backend
    container_name: api
    ports:
      - 3333:3333
    depends_on:
      db: 
        condition: service_healthy
    networks:
      - fale_mais_api

  site: 
    build: ./frontend
    container_name: site
    depends_on:
      - api
    ports: 
      - 3000:3000
    networks:
      - fale_mais_api

networks:
  fale_mais_api: 
    driver: bridge
